export const path = {
    home: "/",
    about: "/about",
    contact: "/contact",
    policy: "/policy",
    terms: "/terms",
    login: "/login",
    register: "/register",
    follow: "/follow",
    history: "/history",
    search: "/search",
    dashboard_info: "/dashboard",
    dashboard_gem: "/dashboard/gem",
    dashboard_manga: "/dashboard/manga",
    dashboard_change_password: "/dashboard/change-password",
    dashboard_chart: "/dashboard/chart",
    dashboard_manage_user: "/dashboard/manage-user",
    dashboard_manage_manga: "/dashboard/manage-manga",
    verify_email: "/verify-email",
    reset_password: "/reset-password",
    create_manga: "/create-manga",
    verify_success: "/verify-success",
}