export const Home = () => {
    return (
        <div>
            <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        <div>
            Home
        </div>
        </div>
    )
}